### ISSUE TITLE
Problem trying to install another version

### ISSUE THREAD

**Issue by juanpy0223** [Revalvier/Thinkpad-E570-Hackintosh#2]
Hello, I installed Big Sur, and it works ok, but when I try to boot High Sierra, Mojave or Catalina, it only restarts, instead of booting installer.... Any sugestion?

The apps Im using now on my Lenovo x230t, work on Mojave and Catalina, better than in Big Sur... Thats why I would like to install Mojave or Catalina

**Comment by Revalvier** [comment]
This has now been fixed with the release of 1.2. Use that.
